-- https://www.geeksforgeeks.org/sql-query-interview-questions/
-- 25 33 34 35 36
CREATE DATABASE PracticeDataBase
;

USE PracticeDataBase
;

CREATE TABLE Student(
	STUDENT_ID INT,
	FIRST_NAME VARCHAR(255),
	LAST_NAME VARCHAR(255),
	GPA FLOAT,
	ENROLLED_DATE DATETIME,
	MAJOR VARCHAR(255)
)
;

CREATE TABLE PROGRAM(
	STUDENT_REF_ID INT,
	PROGRAM_NAME VARCHAR(255),
	PROGRAM_START_DATE DATETIME
)
;

CREATE TABLE SCHOLARSHIP(
	STUDENT_REF_ID INT,
	SCHOLARSHIP_AMOUNT INT,
	SCHOLARSHIP_DATE DATETIME
)
;

INSERT INTO student(STUDENT_ID,FIRST_NAME,LAST_NAME,GPA,ENROLLED_DATE,MAJOR)
 VALUES
	(201, 'Shivansh', 'Mahajan', 8.79, '2021-09-01 09:30', 'Computer Science'),
	(202, 'Umesh', 'Sharma', 8.44, '2021-09-01 08:30', 'Mathematics'),
	(203, 'Rakesh', 'Kumar', 5.6, '2021-09-01 10:00', 'Biology'),
	(204, 'Radha', 'Sharma', 9.2, '2021-09-01 12:45', 'Chemistry'),
	(205, 'Kush', 'Kumar', 7.85, '2021-09-01 08:30', 'Physics'),
	(206, 'Prem', 'Chopra', 9.56, '2021-09-01 09:24', 'History'),
	(207, 'Pankaj', 'Vats', 9.78, '2021-09-01 02:30', 'English'),
	(208, 'Navleen', 'Kaur', 7.0, '2021-09-01 06:30', 'Mathematics')
;

INSERT INTO program(STUDENT_REF_ID,PROGRAM_NAME,PROGRAM_START_DATE)
 VALUES
 	(201, 'Computer Science', '2021-09-01 00:00:00'),
	(202, 'Mathematics', '2021-09-01 00:00:00'),
	(208, 'Mathematics', '2021-09-01 00:00:00'),
	(205, 'Physics', '2021-09-01 00:00:00'),
	(204, 'Chemistry', '2021-09-01 00:00:00'),
	(207, 'Psychology', '2021-09-01 00:00:00'),
	(206, 'History', '2021-09-01 00:00:00'),
	(203, 'Biology', '2021-09-01 00:00:00')
;

INSERT INTO scholarship(STUDENT_REF_ID,SCHOLARSHIP_AMOUNT,SCHOLARSHIP_DATE)
 VALUES
	(201, 5000, '2021-10-15 00:00:00'),
	(202, 4500, '2022-08-18 00:00:00'),
	(203, 3000, '2022-01-25 00:00:00'),
	(204, 4000, '2021-10-15 00:00:00')
;


SELECT UPPER(FIRST_NAME) AS STUDENT_NAME
FROM student
;

SELECT DISTINCT(MAJOR) AS MAJORS
FROM student
;

SELECT MAJOR 
FROM student
GROUP BY MAJOR
;

SELECT SUBSTRING(FIRST_NAME,1,3) AS FIRST_NAME
FROM student
;

SELECT INSTR(FIRST_NAME,'a') AS POSITION_FOUND
FROM (
	SELECT FIRST_NAME
	FROM STUDENT
	WHERE STUDENT_ID = 201
) AS NAME_OF_STUDENT;

SELECT MAJOR,LENGTH(MAJOR) AS LENGTH_OF_MAJOR
FROM student
GROUP BY MAJOR
;

SELECT DISTINCT MAJOR,LENGTH(MAJOR) AS LENGTH_OF_MAJOR
FROM student
;

SELECT REPLACE(first_name,'a','A')
FROM student;

SELECT CONCAT(first_name,' ',last_name) AS COMPLETE_NAME
FROM student
;

SELECT *
FROM student
ORDER BY first_name, Major DESC
;

SELECT *
FROM student
WHERE first_name = 'Prem' OR first_name = 'Shivansh'
;

SELECT *
FROM student
WHERE first_name NOT IN ('Prem','Shivansh')
;

SELECT *
FROM student
WHERE first_name LIKE '%a'
;

SELECT *
FROM student
WHERE FIRST_NAME LIKE '_____a'
;

SELECT *
FROM student
WHERE GPA BETWEEN 9.00 AND 9.99
;

SELECT 
	COUNT(STUDENT_ID) AS TOTAL_COUNT,		
	MAJOR
FROM student
GROUP BY MAJOR
HAVING MAJOR = 'Computer Science'
;

SELECT CONCAT(FIRST_NAME,' ',LAST_NAME) AS FULL_NAME
FROM student
WHERE GPA BETWEEN 8.5 AND 9.5
;

SELECT
	MAJOR,
	COUNT(STUDENT_ID) AS NO_OF_STUDENTS
FROM student
GROUP BY MAJOR
ORDER BY NO_OF_STUDENTS DESC
;

SELECT 
	SD.FIRST_NAME,
	SD.LAST_NAME,
	S.SCHOLARSHIP_AMOUNT,
	S.SCHOLARSHIP_DATE
FROM student AS SD
JOIN scholarship AS S
	ON S.STUDENT_REF_ID = SD.STUDENT_ID
;

SELECT *
FROM STUDENT
WHERE MOD(STUDENT_ID,2) = 1
;

SELECT *
FROM student
WHERE MOD(STUDENT_ID,2) = 0
;

SELECT
	SD.FIRST_NAME,
	SD.LAST_NAME,
	S.SCHOLARSHIP_AMOUNT,
	S.SCHOLARSHIP_DATE
FROM student AS SD
LEFT JOIN scholarship AS S
	ON SD.STUDENT_ID = S.STUDENT_REF_ID
; 

SELECT *
FROM STUDENT
ORDER BY GPA DESC
LIMIT 1
OFFSET 5
;

SELECT 
	S1.FIRST_NAME,
	S1.LAST_NAME,
	S2.FIRST_NAME,
	S2.LAST_NAME,
	S1.GPA
FROM student S1
INNER JOIN student S2
	ON S1.GPA = S2.GPA AND S1.STUDENT_ID<S2.STUDENT_ID
;

SELECT S1.* 
FROM student S1
UNION ALL
SELECT S2.* FROM student S2
ORDER BY STUDENT_ID
;

SELECT 
	SD.STUDENT_ID
FROM student AS SD
LEFT JOIN scholarship AS S
	ON SD.STUDENT_ID = S.STUDENT_REF_ID
WHERE SCHOLARSHIP_AMOUNT IS NULL
;

SELECT
	MAJOR,
	COUNT(STUDENT_ID) AS TOTAL
FROM student
GROUP BY MAJOR
HAVING TOTAL < 4
;

SELECT 
	MAJOR,
	COUNT(STUDENT_ID) AS TOTAL
FROM student
GROUP BY MAJOR
;

SELECT *
FROM student
WHERE STUDENT_ID = (
	SELECT MAX(STUDENT_ID)
	FROM STUDENT
)
;

SELECT *
FROM student
WHERE STUDENT_ID = (
	SELECT MIN(STUDENT_ID)
	FROM STUDENT
)
;

-- won't work in certain version ( LIMIT is not allowed in subquery )
SELECT *
FROM student S1
WHERE S1.STUDENT_ID IN (
	SELECT S2.STUDENT_ID
	FROM student S2
	ORDER BY S2.STUDENT_ID DESC
	LIMIT 5
)
;

SELECT *
FROM student 
LIMIT 5 OFFSET (SELECT COUNT(STUDENT_ID) - 5 FROM STUDENTS ) 
; 

SELECT
	MAJOR,
	MAX(GPA) AS MAX_GPA
FROM student
GROUP BY MAJOR
ORDER BY MAX_GPA
;

SELECT *
FROM student
ORDER BY GPA DESC
LIMIT 1
;

SELECT CURDATE();
SELECT NOW();

UPDATE student 
SET GPA = 7.5
WHERE MAJOR = 'COMPUTER SCIENCE'
;

SELECT MAJOR,ROUND(AVG(GPA),2) AS Average_GPA
FROM student
GROUP BY MAJOR
;

SELECT *
FROM student
ORDER BY GPA DESC
LIMIT 3
;

SELECT *
FROM student
WHERE GPA = (
	SELECT GPA
	FROM STUDENT
	WHERE FIRST_NAME = 'Shivansh' AND LAST_NAME = 'Mahajan'
)
;
